# Tensors Examples

In [1]:
import torch
import numpy as np

In [2]:
# if torch.cuda.is_available():
#     device = torch.device('cuda')
#     x = torch.ones(5, device=device)
#     y = torch.ones(5)
#     y = y.to(device)

# x + y

In [3]:
x = torch.rand(3, requires_grad=True)
x

tensor([0.0740, 0.6388, 0.6508], requires_grad=True)

In [4]:
x = x + 2
x

tensor([2.0740, 2.6388, 2.6508], grad_fn=<AddBackward0>)

In [5]:
z = x * x * 2
z

tensor([ 8.6032, 13.9267, 14.0535], grad_fn=<MulBackward0>)

In [6]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.retain_grad()
z.backward(v)


In [7]:
z.grad

tensor([0.1000, 1.0000, 0.0010])

In [8]:
# z.requires_grad(False)
# x.detach()

# with torch.no_grad():

In [9]:
x.detach()

tensor([2.0740, 2.6388, 2.6508])

In [10]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(1):
    model_outputs = (weights*3).sum()
    
    model_outputs.backward()

In [11]:
weights.grad

tensor([3., 3., 3., 3.])